// src/cart.test.js — Generated by IBM Bob 2.0 (BugRep-AI)
// Strict assertion: must NOT be weakened to make the test pass artificially.
const { calculateTotal } = require('./cart');

test('calculateTotal handles empty cart safely without negative values or NaN', () => {
  const items = [];
  const total = calculateTotal(items, 10);
  expect(total).toBe(0);
});

test('calculateTotal returns correct total for non-empty cart with discount', () => {
  const items = [{ price: 50 }, { price: 50 }];
  const total = calculateTotal(items, 10); // 100 - 10% = 90
  expect(total).toBe(90);
});

test('calculateTotal never returns a negative value even with extreme discount', () => {
  const items = [{ price: 10 }];
  const total = calculateTotal(items, 200); // Would be -10 without guard
  expect(total).toBeGreaterThanOrEqual(0);
});
