// src/cart.fixture.js
// BUGGY reference implementation — do NOT edit this file.
// This is the permanent "before" snapshot used by the Test Agent for the RED
// run and by the Report Agent to document root cause.
//
// Known defects (intentional, matching the original bug report):
//   1. No guard for empty items array — discount math on a 0 subtotal is fine
//      numerically but the function doesn't enforce the "never negative" rule.
//   2. No clamp: if discountPercentage > 100, finalTotal is negative.
//   3. No input validation: undefined/NaN/Infinity discount and missing/negative
//      item prices are all silently accepted and produce nonsense results.

function calculateTotal(items, discountPercentage) {
  let subtotal = items.reduce((sum, item) => sum + item.price, 0);
  let discount = (subtotal * discountPercentage) / 100;
  return subtotal - discount;
}

module.exports = { calculateTotal };
