// orchestrator.js
// BugRep-AI — Automated bug reproduction & regression patch workflow
// Powered by IBM Bob 2.0

const fs = require('fs');
const { execSync } = require('child_process');

console.log('\n🤖 [BugRep-AI] Initializing IBM Bob 2.0 Agent Workflow...\n');

// ─── Step 0: Reset to buggy state so the script is idempotent ────────────────
const buggyCode = `// src/cart.js
function calculateTotal(items, discountPercentage) {
  let subtotal = items.reduce((sum, item) => sum + item.price, 0);
  // BUG: If items is empty, subtotal is 0, calculating discount can yield NaN or negative
  // values if improper
  let discount = (subtotal * discountPercentage) / 100;
  return subtotal - discount;
}

module.exports = { calculateTotal };
`;
fs.writeFileSync('./src/cart.js', buggyCode);

// ─── Step 1: Document Understanding & Context Load ───────────────────────────
const bugReport = fs.readFileSync('./fixtures/bug_report.txt', 'utf8');
const rules     = fs.readFileSync('./docs/cart_rules.md', 'utf8');

console.log('📄 Step 1: Document Understanding & Context Loaded.');
console.log(`   Bug Report : ${bugReport.trim()}`);
console.log(`\n   Cart Rules :\n${rules.trim()}\n`);

// ─── Step 2: Subagent — Generate Reproduction Test ───────────────────────────
console.log('🔍 Step 2: Bob Subagents executing (Analysing codebase & generating test)...\n');

const generatedTest = `// src/cart.test.js — Generated by IBM Bob 2.0 (BugRep-AI)
// Strict assertion: must NOT be weakened to make the test pass artificially.
const { calculateTotal } = require('./cart');

test('calculateTotal handles empty cart safely without negative values or NaN', () => {
  const items = [];
  const total = calculateTotal(items, 10);
  expect(total).toBe(0);
});

test('calculateTotal returns correct total for non-empty cart with discount', () => {
  const items = [{ price: 50 }, { price: 50 }];
  const total = calculateTotal(items, 10); // 100 - 10% = 90
  expect(total).toBe(90);
});

test('calculateTotal never returns a negative value even with extreme discount', () => {
  const items = [{ price: 10 }];
  const total = calculateTotal(items, 200); // Would be -10 without guard
  expect(total).toBeGreaterThanOrEqual(0);
});
`;

fs.writeFileSync('./src/cart.test.js', generatedTest);
console.log('✅ Step 3: Reproduction test written to src/cart.test.js\n');

// ─── Step 3: Run Test Suite — Expect RED ─────────────────────────────────────
console.log('🔴 Step 4: Running test suite to capture reproduction failure...\n');
let testsFailed = false;
try {
  execSync('npx jest src/cart.test.js --no-coverage', { stdio: 'inherit' });
} catch {
  testsFailed = true;
  console.log('\n⚠️  Expected Result: Tests failed (bug successfully reproduced).\n');
}

if (!testsFailed) {
  console.error('❌ Tests passed on the buggy code — verify src/cart.js contains the bug.');
  process.exit(1);
}

// ─── Step 4: Subagent — Apply Implementation Patch ───────────────────────────
console.log('🔧 Step 5: Bob Agent applying implementation patch...\n');

const patchedCode = `// src/cart.js — Patched by IBM Bob 2.0 (BugRep-AI)
function calculateTotal(items, discountPercentage) {
  if (!items || items.length === 0) {
    return 0; // Guard clause: empty cart always returns 0 (Business Rule #3)
  }
  let subtotal = items.reduce((sum, item) => sum + item.price, 0);
  let discount = (subtotal * discountPercentage) / 100;
  let finalTotal = subtotal - discount;
  return finalTotal < 0 ? 0 : finalTotal; // Business Rule #2: total >= 0
}

module.exports = { calculateTotal };
`;

fs.writeFileSync('./src/cart.js', patchedCode);
console.log('✅ Patch applied to src/cart.js\n');

// ─── Step 5: Re-run Test Suite — Expect GREEN ────────────────────────────────
console.log('🟢 Step 6: Re-running test suite after patch...\n');
try {
  execSync('npx jest src/cart.test.js --no-coverage', { stdio: 'inherit' });
  console.log('\n🎉 SUCCESS: All tests passed! Regression fixed without weakening assertions.');
  console.log('   Proof of session stored in /bob_sessions — see README.md for details.\n');
} catch {
  console.error('\n❌ Tests still failing. Review the patch in src/cart.js.');
  process.exit(1);
}
